spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8588

actable:
  table:
    auto: update
    #create    系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
    #update    系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
    #none     系统不做任何处理。
    #add      新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。 没有用（是要改表名）
    #upforce 系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作强制删除原有数据。

  model:
    pack: com.example.entity
  database:
    type: mysql
#mybatis-plus:
#  #外部化xml配置
#  #config-location: classpath:mybatis-config.xml
#  #指定外部化 MyBatis Properties 配置，通过该配置可以抽离配置，实现不同环境的配置部署
#  #configuration-properties: classpath:mybatis/config.properties
#  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
#  mapper-locations: classpath*:/mapper/*.xml
#  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
#  type-aliases-package: com.gitee.sunchenbin.mybatis.actable.dao.*
